import type { Show } from "@/lib/types";

export const shows: Show[] = [
  {
    id: "turnpike-dickies",
    artist: "Turnpike Troubadours",
    supporting: "Special guest TBA",
    venue: "Dickies Arena",
    city: "Fort Worth",
    date: "2026-09-05",
    startTime: "7:30 PM",
    distanceMiles: 18,
    genre: "Country",
    venueSize: "Arena",
    priceBand: "$$$",
    priceText: "$65+",
    allAges: true,
    source: "Ticketmaster",
    blurb: "A major Texas-country draw in one of DFW's best large-room concert settings.",
    signals: { artistMomentum: 98, venueQuality: 94, rarity: 88, localBuzz: 98, value: 68, significance: 94, proximity: 78, lineup: 76 }
  },
  {
    id: "silverada-magnolia",
    artist: "Silverada",
    supporting: "Local opener",
    venue: "Magnolia Motor Lounge",
    city: "Fort Worth",
    date: "2026-09-04",
    startTime: "9:00 PM",
    distanceMiles: 14,
    genre: "Country",
    venueSize: "Club",
    priceBand: "$$",
    priceText: "$22",
    allAges: false,
    source: "Venue",
    blurb: "A strong touring act in a room small enough to feel like you caught them early.",
    signals: { artistMomentum: 84, venueQuality: 91, rarity: 95, localBuzz: 90, value: 92, significance: 84, proximity: 82, lineup: 79 }
  },
  {
    id: "blues-revelers",
    artist: "The Southside Revelers",
    venue: "The Goat",
    city: "Dallas",
    date: "2026-09-04",
    startTime: "9:30 PM",
    distanceMiles: 7,
    genre: "Blues",
    venueSize: "Tiny",
    priceBand: "Free",
    priceText: "Free",
    allAges: false,
    source: "Community",
    blurb: "No-frills neighborhood blues with a strong value and local-scene score.",
    signals: { artistMomentum: 67, venueQuality: 82, rarity: 91, localBuzz: 89, value: 100, significance: 72, proximity: 94, lineup: 72 }
  },
  {
    id: "indie-deep-ellum",
    artist: "Neon Creek",
    supporting: "June Arc • Westbound Static",
    venue: "Three Links",
    city: "Dallas",
    date: "2026-09-05",
    startTime: "8:00 PM",
    distanceMiles: 9,
    genre: "Indie",
    venueSize: "Club",
    priceBand: "$",
    priceText: "$16",
    allAges: false,
    source: "Independent",
    blurb: "Three-act indie bill with unusually high lineup depth for the ticket price.",
    signals: { artistMomentum: 76, venueQuality: 87, rarity: 89, localBuzz: 88, value: 96, significance: 74, proximity: 91, lineup: 95 }
  },
  {
    id: "americana-granada",
    artist: "Red River Saints",
    supporting: "Mara King",
    venue: "Granada Theater",
    city: "Dallas",
    date: "2026-09-06",
    startTime: "8:00 PM",
    distanceMiles: 8,
    genre: "Americana",
    venueSize: "Theater",
    priceBand: "$$",
    priceText: "$34",
    allAges: true,
    source: "Venue",
    blurb: "A polished theater show with strong room quality, support, and local demand.",
    signals: { artistMomentum: 82, venueQuality: 94, rarity: 82, localBuzz: 86, value: 87, significance: 80, proximity: 92, lineup: 90 }
  },
  {
    id: "metal-factory",
    artist: "Black Harbor",
    supporting: "Ash Crown • Hollow Mile",
    venue: "The Factory in Deep Ellum",
    city: "Dallas",
    date: "2026-09-05",
    startTime: "7:00 PM",
    distanceMiles: 10,
    genre: "Rock",
    venueSize: "Theater",
    priceBand: "$$",
    priceText: "$39",
    allAges: true,
    source: "Ticketmaster",
    blurb: "High-energy touring rock package with a deep bill and strong crowd demand.",
    signals: { artistMomentum: 88, venueQuality: 89, rarity: 80, localBuzz: 91, value: 80, significance: 82, proximity: 90, lineup: 93 }
  },
  {
    id: "singer-songwriter-kessler",
    artist: "Caroline Hale",
    venue: "The Kessler Theater",
    city: "Dallas",
    date: "2026-09-03",
    startTime: "8:00 PM",
    distanceMiles: 12,
    genre: "Singer-Songwriter",
    venueSize: "Theater",
    priceBand: "$$",
    priceText: "$28",
    allAges: true,
    source: "Venue",
    blurb: "An intimate listening-room pairing that scores especially well on venue fit.",
    signals: { artistMomentum: 78, venueQuality: 97, rarity: 91, localBuzz: 82, value: 90, significance: 78, proximity: 86, lineup: 74 }
  },
  {
    id: "brewery-folk",
    artist: "Oak & Ember Duo",
    venue: "Vector Brewing",
    city: "Dallas",
    date: "2026-09-04",
    startTime: "7:00 PM",
    distanceMiles: 5,
    genre: "Folk",
    venueSize: "Tiny",
    priceBand: "Free",
    priceText: "Free",
    allAges: true,
    outdoor: true,
    source: "Community",
    blurb: "A casual free patio set that rises because it's close, easy, and genuinely good value.",
    signals: { artistMomentum: 58, venueQuality: 76, rarity: 80, localBuzz: 78, value: 100, significance: 65, proximity: 98, lineup: 68 }
  },
  {
    id: "stadium-pop",
    artist: "Global Pop Tour",
    supporting: "Two national openers",
    venue: "AT&T Stadium",
    city: "Arlington",
    date: "2026-09-06",
    startTime: "7:00 PM",
    distanceMiles: 22,
    genre: "Pop",
    venueSize: "Stadium",
    priceBand: "$$$",
    priceText: "$110+",
    allAges: true,
    source: "Ticketmaster",
    blurb: "Massive production and cultural significance, balanced against price and distance.",
    signals: { artistMomentum: 100, venueQuality: 89, rarity: 90, localBuzz: 100, value: 52, significance: 100, proximity: 72, lineup: 91 }
  }
];
