import type { Venue } from "@/lib/types";

// Phase 2 seed registry. These are intentionally source-first: every venue tells
// the ingestion layer where its public event calendar lives and how we expect to collect it.
export const venues: Venue[] = [
  {
    id: "trees-dallas",
    name: "Trees",
    city: "Dallas",
    state: "TX",
    venueSize: "Club",
    websiteUrl: "https://treesdallas.com/",
    calendarUrl: "https://treesdallas.com/shows/",
    collection: "venue-page",
    genres: ["Rock", "Alternative", "Metal", "Indie", "Hip-Hop"],
  },
  {
    id: "kessler-theater",
    name: "The Kessler Theater",
    city: "Dallas",
    state: "TX",
    venueSize: "Theater",
    websiteUrl: "https://thekessler.org/",
    calendarUrl: "https://thekessler.org/",
    collection: "venue-page",
    genres: ["Americana", "Singer-Songwriter", "Rock", "Soul", "Jazz"],
  },
  {
    id: "granada-theater",
    name: "Granada Theater",
    city: "Dallas",
    state: "TX",
    venueSize: "Theater",
    websiteUrl: "https://www.granadatheater.com/",
    calendarUrl: "https://www.granadatheater.com/calendar",
    collection: "venue-page",
    genres: ["Rock", "Indie", "Country", "Electronic", "Alternative"],
  },
  {
    id: "sundown-granada",
    name: "Sundown at Granada",
    city: "Dallas",
    state: "TX",
    venueSize: "Tiny",
    websiteUrl: "https://www.sundownatgranada.com/",
    calendarUrl: "https://www.sundownatgranada.com/",
    collection: "venue-page",
    genres: ["Singer-Songwriter", "Indie", "Americana", "Local"],
  },
  {
    id: "double-wide",
    name: "Double Wide",
    city: "Dallas",
    state: "TX",
    venueSize: "Tiny",
    websiteUrl: "https://doublewidedallas.com/",
    calendarUrl: "https://doublewidedallas.com/shows/",
    collection: "venue-page",
    genres: ["Rock", "Country", "Punk", "Local"],
  },
  {
    id: "adairs-saloon",
    name: "Adair's Saloon",
    city: "Dallas",
    state: "TX",
    venueSize: "Tiny",
    websiteUrl: "https://adairssaloon.com/",
    calendarUrl: "https://adairssaloon.com/content/live-music/",
    collection: "venue-page",
    genres: ["Country", "Americana", "Local", "Singer-Songwriter"],
  },
  {
    id: "tulips-ftw",
    name: "Tulips FTW",
    city: "Fort Worth",
    state: "TX",
    venueSize: "Club",
    websiteUrl: "https://tulipsftw.com/",
    calendarUrl: "https://tulipsftw.com/",
    collection: "venue-page",
    genres: ["Indie", "Alternative", "Rock", "Country", "Hip-Hop"],
  },
  {
    id: "billy-bobs-texas",
    name: "Billy Bob's Texas",
    city: "Fort Worth",
    state: "TX",
    venueSize: "Theater",
    websiteUrl: "https://www.billybobstexas.com/",
    calendarUrl: "https://www.billybobstexas.com/events",
    collection: "venue-page",
    genres: ["Country", "Texas Country", "Americana"],
  },
  {
    id: "magnolia-motor-lounge",
    name: "Magnolia Motor Lounge",
    city: "Fort Worth",
    state: "TX",
    venueSize: "Club",
    websiteUrl: "https://www.magnoliamotorlounge.com/",
    calendarUrl: "https://www.magnoliamotorlounge.com/",
    collection: "venue-page",
    genres: ["Country", "Texas Country", "Rock", "Americana"],
  },
  {
    id: "tannahills",
    name: "Tannahill's Music Hall & Lounge",
    city: "Fort Worth",
    state: "TX",
    venueSize: "Theater",
    websiteUrl: "https://www.tannahills.com/",
    calendarUrl: "https://www.tannahills.com/",
    collection: "venue-page",
    genres: ["Country", "Rock", "Americana", "Pop"],
  },
  {
    id: "dickies-arena",
    name: "Dickies Arena",
    city: "Fort Worth",
    state: "TX",
    venueSize: "Arena",
    websiteUrl: "https://dickiesarena.com/",
    collection: "ticketmaster",
    genres: ["All"],
  },
  {
    id: "att-stadium",
    name: "AT&T Stadium",
    city: "Arlington",
    state: "TX",
    venueSize: "Stadium",
    websiteUrl: "https://attstadium.com/",
    collection: "ticketmaster",
    genres: ["All"],
  },
];

export const venueByName = new Map(venues.map((venue) => [venue.name.toLowerCase(), venue]));
